channels:
  - conda-forge
  - bioconda
  - r
dependencies:
  - bioconductor-deseq2 >=1.34
  - bioconductor-edger >=3.36
  - r-psych >=1.5
  - r-mass >=7.3
  - r-ggplot2 >=3.1
  - r-ggpubr >=0.1
  - r-data.table >=1.14

