---
title: "DysRegNetR tests"
output: html_notebook
---

```{r}
library(data.table)
```

```{r}
count_path <- "C:/Users/kerst/Desktop/MastersThesis/count_data/BRCA/full/raw.csv"
network_file <- "C:/Users/kerst/Desktop/MastersThesis/data/networks/HTRIdb_corr.csv"
meta_file <- "C:/Users/kerst/Desktop/MastersThesis/count_data/BRCA/full/samples.csv"

raw_counts <- as.matrix(fread(count_path), rownames = "V1")
network <- fread(network_file)[,V1:=NULL][,.(tf,tg)]

meta <- fread(meta_file)
meta <- as.data.frame(meta)
rownames(meta) <- meta$id
meta$id <- NULL
meta <- meta[colnames(raw_counts),]

```

```{r}
source("DysRegNet.R")


drnr <- DysRegNetR(counts=raw_counts,
                   network=network,
                   meta=meta,
                   design = tg ~ log(tf),
                   con_col = "class",
                   norm_method = "mrn",
                   model_type = "negative-binomial",
                   cor_method = "log-pearson",
                   residual_type = "deviance",
                   cooks_filter = T,
                   case_for_disp = T)

drnr <- normalize(drnr)
drnr <- corFilter(drnr)
drnr <- buildModels(drnr)
drnr <- gofFilter(drnr)

drnr
```



```{r}
res <- getResults(drnr, norm_filter = T)

```


```{r}
source("DysRegNet.R")


regulations <- sample(names(drnr@models),1)

case_outlier <- getResults(drnr, regulations = regulations, criterion = "direction", residual_type = "deviance", rating_method = "z-scores", norm_filter = F)

plot(drnr, type = "count_scatter", regulations = regulations, case_outlier = case_outlier, condition = "all", show_sd = F)

plot(drnr, type = "qq", regulations = regulations)
#normality_test(resids)


```

```{r}
source("DysRegNet.R")
plot(drnr, type = "norm_test")
```

